services:
  - type: web
    name: ladder-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python init_db.py && python migrate_to_postgres.py && gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: ladder-db
          property: connectionString

databases:
  - name: ladder-db
    plan: free 