services:
  - type: web
    name: ladder-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: mkdir -p /data/db && ls -la /data && python migrate_db_location.py && python init_db.py && python add_whitelist_table.py && gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"
    disk:
      name: database
      mountPath: /data
      sizeGB: 1 