services:
  - type: web
    name: ladder-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -c "import os; print('DATABASE_URL exists:', os.environ.get('DATABASE_URL') is not None); print('DATABASE_URL:', os.environ.get('DATABASE_URL')); print('RENDER:', os.environ.get('RENDER'))" && python init_db.py && python migrate_to_postgres.py && gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: ladder-db
          property: connectionString
      - key: RENDER
        value: "true"

databases:
  - name: ladder-db
    plan: free 